


[[time-scale-components]]
== Time scale components and units

=== General

The explicit forms of time scale units are represented in this clause.

=== Calendar year and years duration

The calendar year and years duration is represented as follows:

[source]
----
[!]["-"][i]["Y"]
----

[example]
'12Y', duration, twelve years

[example]
'-12Y', date, twelve years before year 0


=== Calendar month and months duration

The calendar month and months duration is represented as follows:

[source]
----
[i]["M"]
----


[example]
'8M', 8 months


=== Calendar week of year and weeks duration

The calendar week of year number and weeks duration is represented as
follows:

[source]
----
[!]["-"][i]["W"]
----


[example]
'10W', duration, ten weeks

[example]
'-10W', negative duration, the tenth last week of the year


When a negative calendar week of year represents a date, the negative
value is to represent the number of weeks counting in reverse from the
end of the calendar year, where the last week of the year is
represented by the integer value '-1'.



=== Calendar day of month and days duration

The calendar day of month and days duration is represented as follows:

[source]
----
[i]["D"]
----


[example]
'25D', 25 days

When a negative calendar day of month represents a date, the negative
value is to represent the number of days counting in reverse from the
end of the calendar month, where the last day of the month is
represented by the integer value '-1'.


=== Calendar day of week

The calendar day of week is represented as the following time scale component:

[source]
----
[i]["K"]
----

Where,

* [i] represents the ordinal day number in the calendar week;
valid values of [i] are the integers 1 to 7, representing Monday to Sunday,
in accordance with "The week calendar" specified in <<ISO8601-1,clause 4.2.2>>.


[example]
'1K', calendar day of week Monday

[example]
'3K', calendar day of week Wednesday

[example]
'7K', calendar day of week Sunday


=== Calendar day of year

The calendar day of year is represented as the following time scale component:

[source]
----
[i]["O"]
----


[example]
'350O'    (ordinal day 350 of the calendar year)


When a negative calendar day of year represents a date, the negative
value is to represent the number of days counting in reverse from the
end of the calendar year, where the last day of the year is represented
by the integer value '-1'.


=== Clock hour and hours duration

Clock hour and hours duration is represented as follows:

[source]
----
[i]["H"]
----


[example]
'6H'   (six hours)


=== Clock minute and minutes duration

Clock minute and minutes duration is represented as follows:

[source]
----
[i]["M"]
----


[example]
'30M'  (30 minutes)


=== Clock second and seconds duration

Clock second and seconds duration is represented as follows:

[source]
----
[i]["S"]
----


[example]
'30S'   (30 seconds)


When a negative clock second represents a time, the negative value is
to represent the number of seconds counting in reverse from the end of
the clock minute, where the last second of the minute is represented by
the integer value '-1'.


=== Decade

The decade is represented as the following time scale component:

[source]
----
[i]["U"]
----


[example]
'196U' (the 1960s)


=== Century

The century is represented as the following time scale component:

[source]
----
[i]["C"]
----


[example]
'19C'  (the 1900s)



[[time-shift]]
=== Time shift

A time shift is used to represent the shift of local standard time
against UTC.

The representation of time shift is represented as follows, and is denoted
as [shiftE] within this document.

[source]
----
["Z"][!]["-"][timeE]
----

Where,

* the leading minus sign (["-"]) is only applied when the time shift
  expressed is behind UTC, it shall be omitted if the time shift is
  ahead of or equal to UTC.

[example]
'Z-5H', five hours behind UTC.

[example]
'Z6H0M', six hours ahead of UTC; the expression '0M' may be omitted
in accordance with <<representations-omission>>.

[example]
'Z8H30M10S', eight hours, thirty minutes and ten seconds ahead of UTC.

A single ["Z"] with the [timeE] portion empty, in accordance with the
rules specified in <<representations-omission>>, indicates that the
time shift from UTC of day is zero, and is functionally equivalent to
the representation [Z0H0M].

[example]
'Z', zero time shift from UTC.

[example]
'Z0H0M', zero time shift from UTC.


[[value-restriction]]
=== Value restrictions

[[negative-values]]
==== Negative values

Certain time scale components are allowed to accept a negative integer
as their value in [i].

[[leading-zero]]
==== Leading zeros

Leading zeros in an explicit form date time representation shall be omitted.

[example]
The calendar month January is expressed as '1M', not '01M'.


[[omission-zero]]
==== Omission of zero valued components

Time scale components within an explicit form that has a value of '0'
may be omitted entirely with its corresponding designator.

[example]
'1985Y4M15DT15H' and '1985Y4M15DT15H0M0S' can be both used to express
the time 3 p.m on April 15th, 1985 in the Gregorian calendar.
